name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          sudo apt update
          sudo apt install -y chromedriver

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build application
        run: ./gradlew build

      - name: Start application
        run: |
          nohup java -jar build/libs/app.jar &
        working-directory: ./

      - name: Run tests
        run: ./gradlew test

      - name: Validate error messages in tests
        run: |
          grep -q 'Неверный логин или пароль' build/reports/tests/test/index.html || exit 1
